// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function DeepProbe(arg1, arg2) {
  return window['go']['main']['App']['DeepProbe'](arg1, arg2);
}

export function DeleteTask(arg1, arg2) {
  return window['go']['main']['App']['DeleteTask'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetVariants(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetVariants'](arg1, arg2, arg3);
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function PauseTask(arg1) {
  return window['go']['main']['App']['PauseTask'](arg1);
}

export function PollWatch(arg1) {
  return window['go']['main']['App']['PollWatch'](arg1);
}

export function Probe(arg1) {
  return window['go']['main']['App']['Probe'](arg1);
}

export function ResumeTask(arg1) {
  return window['go']['main']['App']['ResumeTask'](arg1);
}

export function RevealOutput(arg1) {
  return window['go']['main']['App']['RevealOutput'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function StartDownload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4, arg5);
}

export function StartWatch(arg1) {
  return window['go']['main']['App']['StartWatch'](arg1);
}

export function StopWatch(arg1) {
  return window['go']['main']['App']['StopWatch'](arg1);
}
