// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sniffer} from '../models';
import {main} from '../models';
import {downloader} from '../models';

export function CheckFFmpeg():Promise<string>;

export function DeepProbe(arg1:string,arg2:number):Promise<Array<sniffer.Candidate>>;

export function DeleteTask(arg1:string,arg2:boolean):Promise<void>;

export function GetConfig():Promise<main.DlConfig>;

export function GetVariants(arg1:string,arg2:string,arg3:string):Promise<Array<downloader.Variant>>;

export function ListTasks():Promise<Array<main.TaskInfo>>;

export function PauseTask(arg1:string):Promise<void>;

export function PollWatch(arg1:string):Promise<sniffer.WatchUpdate>;

export function Probe(arg1:string):Promise<Array<sniffer.Candidate>>;

export function ResumeTask(arg1:string):Promise<void>;

export function RevealOutput(arg1:string):Promise<void>;

export function SetConfig(arg1:main.DlConfig):Promise<void>;

export function StartDownload(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function StartWatch(arg1:string):Promise<string>;

export function StopWatch(arg1:string):Promise<void>;
